export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_CARTS = "UPDATE_CARTS";
export const EMPTY_CART = "EMPTY_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const TOGGLE_CART_PREVIEW = "TOGGLE_CART_PREVIEW";
export const CLOSE_CART_PREVIEW = "CLOSE_CART_PREVIEW";
