export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const OPEN_PROFILE_MENU = "OPEN_PROFILE_MENU";
export const CLOSE_PROFILE_MENU = "CLOSE_PROFILE_MENU";
export const OPEN_SEARCH_MENU = "OPEN_SEARCH_MENU";
export const CLOSE_SEARCH_MENU = "CLOSE_SEARCH_MENU";
