import Link from "next/link";
import ConnectedGuard from "../components/guards/connectedGuard";
import Layout from "../components/vitrine/Layout";

export default function Privacy(props) {
  return (
    <ConnectedGuard>
      <Layout
        title={"Privacy policy"}
        description={
          "The use and disclosure of your information when you use the service, and your privacy rights and how the law protects you."
        }
      >
        <div style={{ padding: "20px", fontSize: "13px" }}>
          <h1>Privacy policy</h1>
          <p>Last updated: March 31, 2024</p>
          <p>
            This privacy policy describes our policies and procedures on the
            collection, use and disclosure of your information when you use the
            service, and tells you about your privacy rights and how the law
            protects you.
          </p>
          <p>
            We use your personal data to provide and improve the service. By
            using the Service, You agree to the collection and use of
            information in accordance with this privacy policy. This privacy
            policy was created with the help of the{" "}
            <Link
              href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
              rel="noreferrer"
              target="_blank"
            >
              Free Privacy Policy Generator
            </Link>
            .
          </p>
          <h1>Interpretation and definitions</h1>
          <h2>Interpretation</h2>
          <p>
            Words whose initial letter is capitalized have meanings defined
            under the following conditions. The following definitions shall have
            the same meaning regardless of whether they appear in singular or in
            plural.
          </p>
          <h2>Definitions</h2>
          <p>For the purposes of this privacy policy:</p>
          <ul>
            <li>
              <p>
                <strong>Account</strong> means a unique account created for you
                to access our Service or parts of our Service.
              </p>
            </li>
            <li>
              <p>
                <strong>Company</strong> (referred to as either &quot;the
                Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                &quot;Our&quot; in this Agreement) refers to cyber-mall, Sousse
                4000, Tunisia.
              </p>
            </li>
            <li>
              <p>
                <strong>Cookies</strong> are small files that are placed on your
                computer, mobile device or any other device by a website,
                containing the details of your browsing history on that website
                among its many uses.
              </p>
            </li>
            <li>
              <p>
                <strong>Country</strong> refers to: Tunisia
              </p>
            </li>
            <li>
              <p>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </p>
            </li>
            <li>
              <p>
                <strong>Personal data</strong> is any information that relates
                to an identified or identifiable individual.
              </p>
            </li>
            <li>
              <p>
                <strong>Service</strong> refers to the Website.
              </p>
            </li>
            <li>
              <p>
                <strong>Service provider</strong> means any natural or legal
                person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the
                Company to facilitate the Service, to provide the Service on
                behalf of the Company, to perform services related to the
                Service or to assist the Company in analyzing how the Service is
                used.
              </p>
            </li>
            <li>
              <p>
                <strong>Usage data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the
                duration of a page visit).
              </p>
            </li>
            <li>
              <p>
                <strong>Website</strong> refers to cyber-mall, accessible from{" "}
                <Link
                  href="https://www.cyber-mall.tn"
                  rel="noreferrer"
                  target="_blank"
                >
                  https://www.cyber-mall.tn
                </Link>
              </p>
            </li>
            <li>
              <p>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </p>
            </li>
          </ul>
          <h1>Collecting and using your personal data</h1>
          <h2>Types of data collected</h2>
          <h3>Personal data</h3>
          <p>
            While using our service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul>
            <li>
              <p>Email address</p>
            </li>
            <li>
              <p>Usage data</p>
            </li>
          </ul>
          <h3>Usage data</h3>
          <p>
            Usage data is collected automatically when using the service.
          </p>
          <p>
            Usage data may include information such as Your device&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that You visit, the time and date
            of Your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <p>
            When you access the service by or through a mobile device, we may
            collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile
            device&apos;s unique ID, the IP address of Your mobile device, Your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that your browser sends whenever you
            visit our service or when you access the service by or through a
            mobile device.
          </p>
          <h3>Tracking technologies and cookies</h3>
          <p>
            We use cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. The tracking
            technologies used are beacons, tags and scripts to collect and track
            information and to improve and analyze Our Service. The technologies
            we use may include:
          </p>
          <ul>
            <li>
              <strong>Cookies or browser cookies.</strong> A cookie is a small
              file placed on your device. You can instruct your browser to
              refuse all cookies or to indicate when a cookie is being sent.
              However, if You do not accept cookies, you may not be able to use
              some parts of our service. Unless you have adjusted your browser
              settings so that it will refuse Cookies, our Service may use
              Cookies.
            </li>
            <li>
              <strong>Web beacons.</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              (also referred to as clear gifs, pixel tags and single-pixel gifs)
              that permit the Company, for example, to count users who have
              visited those pages or opened an email and for other related
              website statistics (for example, recording the popularity of a
              certain section and verifying system and server integrity).
            </li>
          </ul>
          <p>
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
            Cookies. Persistent Cookies remain on your personal computer or
            mobile device when you go offline, while Session Cookies are deleted
            as soon as you close Your web browser. Learn more about cookies in
            the{" "}
            <Link
              href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking"
              rel="noreferrer"
              target="_blank"
            >
              Free Privacy Policy website
            </Link>{" "}
            article.
          </p>
          <p>
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </p>
          <ul>
            <li>
              <p>
                <strong>Necessary / essential cookies</strong>
              </p>
              <p>Type: Session cookies</p>
              <p>Administered by: Us</p>
              <p>
                Purpose: These Cookies are essential to provide You with
                services available through the website and to enable you to use
                some of its features. They help to authenticate users and prevent
                fraudulent use of user accounts. Without these Cookies, the
                services that You have asked for cannot be provided, and We only
                use these Cookies to provide You with those services.
              </p>
            </li>
            <li>
              <p>
                <strong>Cookies policy / Cookies acceptance notice</strong>
              </p>
              <p>Type: Persistent cookies</p>
              <p>Administered by: Us</p>
              <p>
                Purpose: These cookies identify whether users have accepted the
                use of cookies on the website.
              </p>
            </li>
            <li>
              <p>
                <strong>Functionality cookies</strong>
              </p>
              <p>Type: Persistent cookies</p>
              <p>Administered by: Us</p>
              <p>
                Purpose: These cookies allow us to remember the choices you make
                when You use the website, such as remembering your login details
                or language preference. The purpose of these Cookies is to
                provide You with a more personal experience and to avoid You
                having to re-enter your preferences every time you use the
                website.
              </p>
            </li>
          </ul>
          <p>
            For more information about the cookies we use and your choices
            regarding cookies, please see our cookies policy or the cookies
            section of our privacy policy.
          </p>
          <h2>Use of your personal data</h2>
          <p>
            The Company may use Personal Data for the following purposes:
          </p>
          <ul>
            <li>
              <p>
                <strong>To provide and maintain our Service</strong>, including
                to monitor the usage of our Service.
              </p>
            </li>
            <li>
              <p>
                <strong>To manage Your Account:</strong> to manage Your
                registration as a user of the Service. The personal data you
                provide can give You access to different functionalities of the
                Service that are available to You as a registered user.
              </p>
            </li>
            <li>
              <p>
                <strong>For the performance of a contract:</strong> the
                development, compliance and undertaking of the purchase contract
                for the products, items or services you have purchased or of any
                other contract with Us through the Service.
              </p>
            </li>
            <li>
              <p>
                <strong>To contact You:</strong> to contact You by email,
                telephone calls, SMS, or other equivalent forms of
                communication, such as mobile application push notifications
                regarding updates or informative communications related to the
                functionalities, products or contracted services, including
                security updates, when necessary or reasonable for their
                implementation.
              </p>
            </li>
            <li>
              <p>
                <strong>To provide You</strong> with news, special offers and
                general information about other goods, services and events which
                we offer that are similar to those that you have already
                purchased or enquired about unless You have opted not to receive
                such information.
              </p>
            </li>
            <li>
              <p>
                <strong>To manage Your requests:</strong> to attend and manage
                Your requests to Us.
              </p>
            </li>
            <li>
              <p>
                <strong>For business transfers:</strong> We may use Your
                information to evaluate or conduct a merger, divestiture,
                restructuring, reorganization, dissolution, or other sale or
                transfer of some or all of our assets, whether as a going
                concern or as part of bankruptcy, liquidation, or similar
                proceeding, in which personal data held by us about our Service
                users is among the assets transferred.
              </p>
            </li>
            <li>
              <p>
                <strong>For other purposes</strong>: we may use your information
                for other purposes, such as data analysis, identifying usage
                trends, determining the effectiveness of our promotional
                campaigns and to evaluate and improve our service, products,
                services, marketing and your experience.
              </p>
            </li>
          </ul>
          <p>
            We may share your personal information in the following situations:
          </p>
          <ul>
            <li>
              <strong>With service providers:</strong> we may share your
              personal information with service providers to monitor and analyze
              the use of our service, to contact you.
            </li>
            <li>
              <strong>For business transfers:</strong> we may share or transfer
              Your personal information in connection with, or during
              negotiations of, any merger, sale of Company assets, financing, or
              acquisition of all or a portion of Our business to another
              company.
            </li>
            <li>
              <strong>With affiliates:</strong> we may share your information
              with Our affiliates, in which case we will require those
              affiliates to honor this privacy policy. Affiliates include our
              parent company and any other subsidiaries, joint venture partners
              or other companies that We control or that are under common
              control with Us.
            </li>
            <li>
              <strong>With business partners:</strong> we may share your
              information with our business partners to offer you certain
              products, services or promotions.
            </li>
            <li>
              <strong>With other users:</strong> when you share personal
              information or otherwise interact in the public areas with other
              users, such information may be viewed by all users and may be
              publicly distributed outside.
            </li>
            <li>
              <strong>With your consent</strong>: we may disclose your personal
              information for any other purpose with your consent.
            </li>
          </ul>
          <h2>Retention of your personal data</h2>
          <p>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this privacy policy. We will
            retain and use your personal data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </p>
          <p>
            The Company will also retain usage data for internal analysis
            purposes. Usage data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer periods.
          </p>
          <h3>Other legal requirements</h3>
          <p>
            The Company may disclose your personal data in the good faith belief
            that such action is necessary to:
          </p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>
              Prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>
              Protect the personal safety of Users of the Service or the public
            </li>
            <li>Protect against legal liability</li>
          </ul>
          <h2>Security of your personal data</h2>
          <p>
            The security of your personal data is important to us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your personal data, we
            cannot guarantee its absolute security.
          </p>
          <h1>Children&apos;s privacy</h1>
          <p>
            Our service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If you are a parent or guardian and you are
            aware that your child has provided us with personal data, please
            contact us. If we become aware that we have collected personal data
            from anyone under the age of 13 without verification of parental
            consent, we take steps to remove that information from our servers.
          </p>
          <p>
            If we need to rely on consent as a legal basis for processing your
            information and your country requires consent from a parent, we may
            require your parent&apos;s consent before we collect and use that
            information.
          </p>
          <h1>Links to other websites</h1>
          <p>
            Our service may contain links to other websites that are not
            operated by us. If you click on a third-party link, you will be
            directed to that third party&apos;s site. We strongly advise you to
            review the privacy policy of every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third-party sites or
            services.
          </p>
          <h1>Changes to this privacy policy</h1>
          <p>
            We may update our privacy policy from time to time. We will notify
            you of any changes by posting the new privacy policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the
            &quot;Last updated&quot; date at the top of this privacy policy.
          </p>
          <p>
            You are advised to review this privacy policy periodically for any
            changes. Changes to this privacy policy are effective when they are
            posted on this page.
          </p>
          <h1>Contact us</h1>
          <p>
            If you have any questions about this privacy policy, you can contact
            us:
          </p>
          <ul>
            <li>
              <p>
                By email:{" "}
                <Link href="mailto:cyber-mall.tn@gmail.com">
                  cyber-mall.tn@gmail.com
                </Link>
              </p>
            </li>
            <li>
              <p>
                By visiting this page on our website:{" "}
                <Link
                  href="https://cyber-mall.tn"
                  rel="noreferrer"
                  target="_blank"
                >
                  https://cyber-mall.tn
                </Link>
              </p>
            </li>
            <li>
              <p>
                By phone number:{" "}
                <Link href="tel:+216 47 010 114">+216 47 010 114</Link>
              </p>
            </li>
          </ul>
        </div>
      </Layout>
    </ConnectedGuard>
  );
}
