export const ActivityDomains = [
  { name: "Vente au détail" },
  { name: "Vente en gros" },
  { name: "Mode et habillement" },
  { name: "Électronique" },
  { name: "Maison et jardin" },
  { name: "Beauté et soins personnels" },
  { name: "Produits alimentaires" },
  { name: "Articles de sport" },
  { name: "Jouets et jeux" },
  { name: "Livres et médias" },
  { name: "Produits pour bébés" },
  { name: "Santé et bien-être" },
  { name: "Accessoires et bijoux" },
  { name: "Automobile" },
  { name: "Informatique et logiciels" },
  { name: "Articles de bureau" },
  { name: "Voyages et loisirs" },
  { name: "Produits pour animaux de compagnie" },
  { name: "Meubles" },
  { name: "Instruments de musique" },
];
