export const ActivityDomains = [
  { name: "Retail" },
  { name: "Wholesale" },
  { name: "Fashion and Clothing" },
  { name: "Electronics" },
  { name: "Home and Garden" },
  { name: "Beauty and Personal Care" },
  { name: "Food Products" },
  { name: "Sporting Goods" },
  { name: "Toys and Games" },
  { name: "Books and Media" },
  { name: "Baby Products" },
  { name: "Health and Wellness" },
  { name: "Accessories and Jewelry" },
  { name: "Automotive" },
  { name: "Computing and Software" },
  { name: "Office Supplies" },
  { name: "Travel and Leisure" },
  { name: "Pet Products" },
  { name: "Furniture" },
  { name: "Musical Instruments" },
  { name: "Cleaning Products" },
  { name: "DIY Products" },
  { name: "Gardening Supplies" },
  { name: "Food and Beverages" },
  { name: "Fitness Equipment" },
  { name: "Party Supplies" },
  { name: "Camping Gear" },
  { name: "School Supplies" },
  { name: "Real Estate" },
  { name: "Finance and Insurance" },
  { name: "Education" },
  { name: "Telecommunications" },
  { name: "Energy and Utilities" },
  { name: "Transportation and Logistics" },
  { name: "Pharmaceutical and Life Sciences" },
  { name: "Technology and Innovation" },
  { name: "Entertainment and Media" },
  { name: "Cultural Products" },
  { name: "Workwear" },
  { name: "Electronic Accessories" },
  { name: "Industrial Equipment" },
  { name: "Medical Equipment" },
  { name: "Tools and Equipment" },
  { name: "Handmade Products" },
  { name: "Office Equipment" },
  { name: "Travel Accessories" },
  { name: "Costume Jewelry" },
  { name: "Perfumery" },
  { name: "Luxury Goods" },
  { name: "Organic Food" },
  { name: "Video Games and Consoles" },
  { name: "Meal Delivery" },
  { name: "Art and Art Supplies" },
  { name: "Interior Decoration" },
  { name: "Fishing Gear" },
  { name: "Hunting Gear" },
  { name: "Photography Equipment" },
  { name: "Fashion Accessories" },
  { name: "Safety Equipment" },
  { name: "Eco-friendly Products" },
  { name: "Extreme Sports Gear" },
  { name: "Sportswear" },
  { name: "Hair Care Products" },
  { name: "Natural Cosmetics" },
  { name: "Skincare Products" },
  { name: "Gadgets and Accessories" },
  { name: "Bags and Luggage" },
  { name: "Watches and Clocks" },
  { name: "Electric Vehicles" },
  { name: "Bicycle Accessories" },
  { name: "Smart Home Products" },
  { name: "Climbing Gear" },
  { name: "Beach Accessories" },
  { name: "Personal Protective Equipment" },
];
